export const ETHERSCAN_BASE_URL = "https://etherscan.io/";
export const BSCSCAN_BASE_URL = "https://bscscan.com/";
export const DOGECHAIN_BASE_URL = "https://explorer.dogechain.dog/";
export const POLYCHAIN_BASE_URL = "https://polygonscan.com/";
export const ARBITRUMCHAIN_BASE_URL = "https://sepolia.arbiscan.io/";
export const GOERLICHAIN_BASE_URL = "https://goerli.etherscan.io/";
export const SEPOLIACHAIN_BASE_URL = "https://sepolia.etherscan.io/";
export const HOLESKYCHAIN_BASE_URL = "https://holesky.etherscan.io/";

export const BASECHAIN_BASE_URL = "https://basescan.org/";
export const AVALANCHECHAIN_BASE_URL = "https://avascan.info/";
export const OPMAINNETCHAIN_BASE_URL = "https://optimistic.etherscan.io/";
export const CRONOSMAINNETCHAIN_BASE_URL = "https://cronoscan.com/";
export const LINEAMAINNETCHAIN_BASE_URL = "https://lineascan.build/";
export const MANTLEMAINNETCHAIN_BASE_URL = "https://explorer.mantle.xyz/";
export const PULSEMAINNETCHAIN_BASE_URL = "https://scan.pulsehotlist.com/#/";
export const FANTOMCHAIN_BASE_URL = "https://ftmscan.com/";
export const GNOSISCHAIN_BASE_URL = "https://gnosisscan.io/";
export const CELOCHAIN_BASE_URL = "https://celoscan.io/";
export const HARMONYCHAIN_BASE_URL = "https://explorer.harmony.one/";
export const BLASTCHAIN_BASE_URL = "https://blastscan.io/";
export const ZETACHAIN_BASE_URL = "https://explorer.zetachain.com/";
//new
export const APECHAIN_BASE_URL = "https://apescan.io/";
export const ARBITRUMNOVACHAIN_BASE_URL = "https://nova.arbiscan.io/";
export const BERACHAIN_BASE_URL = "https://berascan.com/";
export const BTTCCHAIN_BASE_URL = "https://bttcscan.com/";
export const FRAXCHAIN_BASE_URL = "https://fraxscan.com/";
export const MEMECORECHAIN_BASE_URL = "https://memecorescan.io/";
export const MOONBEAMCHAIN_BASE_URL = "https://moonscan.io/";
export const MOONRIVERCHAIN_BASE_URL = "https://moonriver.moonscan.io/";
export const OPBNBCHAIN_BASE_URL = "https://opbnbscan.com/";
export const SCROLLCHAIN_BASE_URL = "https://scrollscan.com/";
export const SONICCHAIN_BASE_URL = "https://sonicscan.org/";
export const SWELLCHAIN_BASE_URL = "https://explorer.swellnetwork.io/";
export const TAIKOALETHIACHAIN_BASE_URL = "https://taikoscan.io/";
export const UNICHAIN_BASE_URL = "https://unichain.blockscout.com/";
export const WEMIXCHAIN_BASE_URL = "https://explorer.wemix.com/";
export const XAICHAIN_BASE_URL = "https://xaiscan.io/";
export const XDCCHAIN_BASE_URL = "https://xdcscan.com/";
export const ZKSYNCERACHAIN_BASE_URL = "https://explorer.zksync.io/";
export const ZIRCUITCHAIN_BASE_URL = "https://explorer.zircuit.com/";

// apechain;
// arbitrumnovachain;
// berachain;
// bttcchain;
// fraxchain;
// memecorechain;
// moonbeamchain;
// moonriverchain;
// opbnbchain;
// scrollchain;
// sonicchain;
// swellchain;
// taikoalethiachain;
// unichain;
// wemixchain;
// xaichain;
// xdcchain;
// zksyncerachain;
// zircuitchain;
